# Generated by Django 6.0.1 on 2026-03-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='payment',
        ),
    ]
