# Generated by Django 6.0.1 on 2026-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_commission_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
