# Generated by Django 6.0.1 on 2026-04-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_remove_recurringorderinstance_last_stock_alert_sent'),
        ('payments', '0006_alter_paymenttransaction_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order_management.order'),
        ),
    ]
