# Generated by Django 6.0.1 on 2026-02-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('verified_purchase_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customeraccount')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
