# Generated by Django 6.0.1 on 2026-02-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerAccount',
            fields=[
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='producer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.TextField()),
                ('business_postcode', models.CharField(max_length=10)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('farm_description', models.TextField(blank=True)),
                ('farm_logo', models.ImageField(blank=True, null=True, upload_to='producer_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='producer_covers/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('organic_certified', models.BooleanField(default=False)),
                ('organic_certification_body', models.CharField(blank=True, max_length=100)),
                ('organic_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('default_lead_time_hours', models.IntegerField(default=48, help_text='Default lead time in hours (minimum 48)')),
                ('delivery_radius_miles', models.IntegerField(default=20, help_text='Maximum delivery distance in miles')),
                ('payout_account_holder', models.CharField(blank=True, max_length=200)),
                ('payout_sort_code', models.CharField(blank=True, max_length=8)),
                ('payout_account_number', models.CharField(blank=True, max_length=8)),
                ('payout_bank_name', models.CharField(blank=True, max_length=100)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='JSON field for business hours')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'producer_accounts',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='ProducerDeliveryPostcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_postcodes', to='producers.produceraccount')),
            ],
            options={
                'db_table': 'producer_delivery_postcodes',
                'unique_together': {('producer', 'postcode')},
            },
        ),
        migrations.CreateModel(
            name='ProducerProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='producers.produceraccount')),
            ],
            options={
                'db_table': 'producer_categories',
                'unique_together': {('producer', 'category_name')},
            },
        ),
    ]
