# Generated by Django 6.0.1 on 2026-02-24 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'educational_content',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FarmStory',
            fields=[
                ('farm_story_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='farm_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm_story',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('stock_time_change', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='product.product')),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('seasonal_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('date_recipe_created', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SettlementReport',
            fields=[
                ('settlement_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, db_column='transaction_id', help_text='Payment transaction reference (placeholder until payments app exists).', max_length=100, null=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('producer', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='settlement_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlement_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProducerSettlementOrder',
            fields=[
                ('settlement_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_column='order_id')),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producer_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_report', models.ForeignKey(db_column='settlement_report_id', on_delete=django.db.models.deletion.CASCADE, related_name='settlement_orders', to='producers.settlementreport')),
            ],
            options={
                'db_table': 'producer_settlement_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurplusDiscount',
            fields=[
                ('surplus_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=20)),
                ('date_discount_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='surplus_discounts', to='product.product')),
            ],
            options={
                'db_table': 'surplus_discount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('recipe_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='linked_recipes', to='product.product')),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='linked_products', to='producers.recipe')),
            ],
            options={
                'db_table': 'products_recipes',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('recipe', 'product'), name='unique_recipe_product_link')],
            },
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_customers', to='producers.recipe')),
            ],
            options={
                'db_table': 'saved_recipes',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('customer', 'recipe'), name='unique_customer_recipe_save')],
            },
        ),
    ]
