# Generated by Django 6.0.1 on 2026-04-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
        ('product', '0002_product_low_stock_threshold_alter_product_image'),
        ('user_accounts', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stock', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='user_accounts.produceraccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='product.product')),
            ],
            options={
                'db_table': 'low_stock_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
