# Generated by Django 6.0.1 on 2026-02-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_alter_inventory_product_and_more'),
        ('product', '0003_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmstory',
            name='producer',
            field=models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='farm_stories', to='user_accounts.produceraccount'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='producer',
            field=models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='user_accounts.produceraccount'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='linked_recipes', to='product.product'),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='user_accounts.customeraccount'),
        ),
        migrations.AlterField(
            model_name='settlementreport',
            name='producer',
            field=models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='settlement_reports', to='user_accounts.produceraccount'),
        ),
    ]
