# Generated by Django 6.0.1 on 2026-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_lowstockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusdiscount',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surplusdiscount',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surplusdiscount',
            name='surplus_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surplusdiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='surplusdiscount',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='surplusdiscount',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='surplusdiscount',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('sold_out', 'sold_out'), ('cancelled', 'cancelled')], default='active', max_length=20),
        ),
    ]
