# Generated by Django 6.0.1 on 2026-04-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_surplusdiscount_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surplusdiscount',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='surplusdiscount',
            name='surplus_quantity',
        ),
    ]
