<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-02-24 23:24

import django.db.models.deletion
=======
# Generated by Django 6.0.1 on 2026-02-28 23:22

import django.db.models.deletion
from django.conf import settings
>>>>>>> origin/main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/main
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'allergen',
<<<<<<< HEAD
                'managed': True,
=======
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_category',
>>>>>>> origin/main
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('producer_id', models.IntegerField()),
=======
>>>>>>> origin/main
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=50)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('availability_status', models.BooleanField(default=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('organic_certified', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/main
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> origin/main
            name='ProductAllergen',
            fields=[
                ('product_allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.allergen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_allergen',
                'managed': True,
<<<<<<< HEAD
=======
                'unique_together': {('product', 'allergen')},
>>>>>>> origin/main
            },
        ),
        migrations.AddField(
            model_name='product',
<<<<<<< HEAD
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
=======
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductAllergen', to='product.allergen'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory'),
        ),
        migrations.CreateModel(
            name='SeasonalAvailability',
            fields=[
                ('seasonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_start_date', models.DateField(blank=True, null=True)),
                ('season_end_date', models.DateField(blank=True, null=True)),
                ('is_year_round', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_availability', to='product.product')),
            ],
            options={
                'db_table': 'seasonal_availability',
                'managed': True,
            },
>>>>>>> origin/main
        ),
    ]
