# Generated by Django 6.0.1 on 2026-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_low_stock_threshold_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_info',
            field=models.TextField(blank=True),
        ),
    ]
