# Generated by Django 6.0.1 on 2026-04-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_best_before_date_product_quality_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality_info',
        ),
    ]
