# Generated by Django 6.0.1 on 2026-04-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_recurringtemplate_recurringorderinstance_and_more'),
        ('product', '0005_product_is_expired'),
        ('user_accounts', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('anon', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customeraccount')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order_management.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
