# Generated by Django 6.0.1 on 2026-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_reviewproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproduct',
            name='review_verified',
            field=models.BooleanField(default=False),
        ),
    ]
