# Generated by Django 6.0.1 on 2026-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_reviewproduct_review_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_threshold_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
