# Generated by Django 6.0.1 on 2026-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_bulk_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bulk_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bulk_threshold_quantity',
        ),
    ]
