# Generated by Django 6.0.1 on 2026-03-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user_accounts', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_postcode', models.CharField(max_length=20)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user_accounts.customeraccount')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('suborder_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='order_management.order')),
                ('producer', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, related_name='producer_suborders', to='user_accounts.produceraccount')),
            ],
            options={
                'db_table': 'suborder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('order_status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('stock_time_change', models.ForeignKey(blank=True, db_column='producer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.produceraccount')),
                ('suborder', models.ForeignKey(db_column='suborder_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='order_management.suborder')),
            ],
            options={
                'db_table': 'order_status_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('suborder', models.ForeignKey(db_column='suborder_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_management.suborder')),
            ],
            options={
                'db_table': 'order_item',
                'managed': True,
            },
        ),
    ]
