# Generated by Django 6.0.1 on 2026-03-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
        ('user_accounts', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('recurring_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurrence_schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_order_date', models.DateField()),
                ('active_status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to='user_accounts.customeraccount')),
            ],
            options={
                'db_table': 'recurring_order',
                'managed': True,
            },
        ),
    ]
