# Generated by Django 6.0.1 on 2026-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_recurringorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
