# Generated by Django 6.0.1 on 2026-04-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_orderitem_original_price_at_purchase'),
        ('user_accounts', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional name for this recurring order', max_length=255)),
                ('recurrence', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('delivery_weekday', models.IntegerField(help_text='0=Monday, 1=Tuesday, ..., 6=Sunday')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('items', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='user_accounts.customeraccount')),
            ],
            options={
                'db_table': 'recurring_template',
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderInstance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instance', to='order_management.order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='order_management.recurringtemplate')),
            ],
            options={
                'db_table': 'recurring_order_instance',
                'unique_together': {('template', 'scheduled_date')},
            },
        ),
        migrations.DeleteModel(
            name='RecurringOrder',
        ),
    ]
