# Generated by Django 6.0.1 on 2026-04-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_recurringtemplate_recurringorderinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderinstance',
            name='last_stock_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
