# Generated by Django 6.0.1 on 2026-04-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_recurringtemplate_recurringorderinstance_and_more'),
    ]

    operations = [
    ]
