# Generated by Django 6.0.1 on 2026-04-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_recurringorderinstance_last_stock_alert_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringorderinstance',
            name='last_stock_alert_sent',
        ),
    ]
