# Generated by Django 6.0.1 on 2026-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_remove_recurringorderinstance_last_stock_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderinstance',
            name='last_stock_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
