# Generated by Django 6.0.1 on 2026-04-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_recurringorderinstance_last_stock_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='fulfillment_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('collect', 'Collection')], default='delivery', max_length=10),
        ),
    ]
