# Generated by Django 6.0.1 on 2026-04-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_remove_fulfillment_method'),
        ('order_management', '0008_suborder_fulfillment_method'),
    ]

    operations = [
    ]
