# Generated by Django 6.0.1 on 2026-04-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_merge_20260430_0248'),
    ]

    operations = [
    ]
