# Generated by Django 6.0.1 on 2026-04-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_remove_fulfillment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='fulfillment_method',
        ),
    ]
