# Generated by Django 6.0.1 on 2026-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_remove_suborder_fulfillment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='fulfillment_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('collection', 'Collection')], default='delivery', max_length=10),
        ),
    ]
