# Generated by Django 6.0.1 on 2026-02-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer'), ('admin', 'Admin')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProducerAccount',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.useraccount')),
            ],
            options={
                'db_table': 'producer_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.useraccount')),
            ],
            options={
                'db_table': 'customer_account',
                'managed': True,
            },
        ),
    ]
