# Generated by Django 6.0.1 on 2026-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceraccount',
            name='bulk_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produceraccount',
            name='bulk_threshold_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
