# Generated by Django 6.0.1 on 2026-02-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shopping_cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'shopping_cart_item',
                'managed': True,
            },
        ),
    ]
