# Generated by Django 6.0.1 on 2026-02-26 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.product'),
            preserve_default=False,
        ),
    ]
