# Generated by Django 6.0.1 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
