<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-02-26 21:30
=======
# Generated by Django 6.0.1 on 2026-03-02 12:12
>>>>>>> origin/main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
