# Generated by Django 6.0.1 on 2026-04-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_producernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producernotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_update', 'Order Update'), ('low_stock', 'Low Stock Alert'), ('low_stock_resolved', 'Low Stock Resolved'), ('general', 'General')], max_length=20),
        ),
    ]
