# Generated by Django 6.0.1 on 2026-04-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_producernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock_available', 'Stock Available'), ('price_drop', 'Price Drop'), ('order_update', 'Order Update'), ('surplus_available', 'Surplus Deal Available'), ('general', 'General')], max_length=20),
        ),
    ]
