# Generated by Django 6.0.1 on 2026-05-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
        ('product', '0009_remove_product_bulk_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producernotification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='producernotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_update', 'Order Update'), ('low_stock', 'Low Stock Alert'), ('low_stock_resolved', 'Low Stock Resolved'), ('seasonal_coming_soon', 'Seasonal Product Coming Soon'), ('general', 'General')], max_length=20),
        ),
    ]
