# Generated by Django 6.0.1 on 2026-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFinancialReport',
            fields=[
                ('financial_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_orders', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_financial_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminSecurity',
            fields=[
                ('security_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_security',
                'managed': True,
            },
        ),
    ]
