# Generated by Django 6.0.1 on 2026-03-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminFinancialReport',
        ),
        migrations.DeleteModel(
            name='AdminSecurity',
        ),
    ]
